apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: tmate
bases:
  # - ../../nginx-ingress
  # - ../../tilt
resources:
  # - tmate-ns.yaml
  - config.yaml
  - ssh-keys-dev.yaml
  - master.yaml
  - postgres.yaml
  - session.yaml
  - master-ingress.yaml
  - session-ingress.yaml
  - tilt-ingress.yaml
  # - tcp-services.yaml
patchesJson6902:
  # - target:
  #     group: extensions
  #     version: v1beta1
  #     kind: Ingress
  #     name: tilt-ingress
  #   path: tilt-ingress-patch.yaml
  # - target:
  #     version: v1
  #     kind: ConfigMap
  #     name: tcp-services
  #     namespace: ingress-nginx
  #   path: tcp-services-patch.yaml
  # - target:
  #     # group: core
  #     version: v1
  #     kind: Service
  #     name: kubemacs-tilt
  #   path: tilt-service-patch.yaml
