{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubemacs.serviceAccountName" . }}
  labels:
{{ include "kubemacs.labels" . | nindent 4 }}
{{- end -}}
